# Mapping of Passport Index country names and aliases to ISO-2 codes, English names, and Thai names

COUNTRY_MAPPING = {
    "Afghanistan": {"iso2": "AF", "name_en": "Afghanistan", "name_th": "อัฟกานิสถาน"},
    "Albania": {"iso2": "AL", "name_en": "Albania", "name_th": "แอลเบเนีย"},
    "Algeria": {"iso2": "DZ", "name_en": "Algeria", "name_th": "แอลจีเรีย"},
    "Andorra": {"iso2": "AD", "name_en": "Andorra", "name_th": "อันดอร์รา"},
    "Angola": {"iso2": "AO", "name_en": "Angola", "name_th": "แองโกลา"},
    "Antigua and Barbuda": {"iso2": "AG", "name_en": "Antigua and Barbuda", "name_th": "แอนติกาและบาร์บูดา"},
    "Argentina": {"iso2": "AR", "name_en": "Argentina", "name_th": "อาร์เจนตินา"},
    "Armenia": {"iso2": "AM", "name_en": "Armenia", "name_th": "อาร์เมเนีย"},
    "Australia": {"iso2": "AU", "name_en": "Australia", "name_th": "ออสเตรเลีย"},
    "Austria": {"iso2": "AT", "name_en": "Austria", "name_th": "ออสเตรีย"},
    "Azerbaijan": {"iso2": "AZ", "name_en": "Azerbaijan", "name_th": "อาเซอร์ไบจาน"},
    "Bahamas": {"iso2": "BS", "name_en": "Bahamas", "name_th": "บาฮามาส"},
    "Bahrain": {"iso2": "BH", "name_en": "Bahrain", "name_th": "บาห์เรน"},
    "Bangladesh": {"iso2": "BD", "name_en": "Bangladesh", "name_th": "บังกลาเทศ"},
    "Barbados": {"iso2": "BB", "name_en": "Barbados", "name_th": "บาร์เบโดส"},
    "Belarus": {"iso2": "BY", "name_en": "Belarus", "name_th": "เบลารุส"},
    "Belgium": {"iso2": "BE", "name_en": "Belgium", "name_th": "เบลเยียม"},
    "Belize": {"iso2": "BZ", "name_en": "Belize", "name_th": "เบลีซ"},
    "Benin": {"iso2": "BJ", "name_en": "Benin", "name_th": "เบนิน"},
    "Bhutan": {"iso2": "BT", "name_en": "Bhutan", "name_th": "ภูฏาน"},
    "Bolivia": {"iso2": "BO", "name_en": "Bolivia", "name_th": "โบลิเวีย"},
    "Bosnia and Herzegovina": {"iso2": "BA", "name_en": "Bosnia and Herzegovina", "name_th": "บอสเนียและเฮอร์เซโกวีนา"},
    "Botswana": {"iso2": "BW", "name_en": "Botswana", "name_th": "บอตสวานา"},
    "Brazil": {"iso2": "BR", "name_en": "Brazil", "name_th": "บราซิล"},
    "Brunei": {"iso2": "BN", "name_en": "Brunei", "name_th": "บรูไน"},
    "Bulgaria": {"iso2": "BG", "name_en": "Bulgaria", "name_th": "บัลแกเรีย"},
    "Burkina Faso": {"iso2": "BF", "name_en": "Burkina Faso", "name_th": "บูร์กินาฟาโซ"},
    "Burundi": {"iso2": "BI", "name_en": "Burundi", "name_th": "บุรุนดี"},
    "Cambodia": {"iso2": "KH", "name_en": "Cambodia", "name_th": "กัมพูชา"},
    "Cameroon": {"iso2": "CM", "name_en": "Cameroon", "name_th": "แคเมอรูน"},
    "Canada": {"iso2": "CA", "name_en": "Canada", "name_th": "แคนาดา"},
    "Cape Verde": {"iso2": "CV", "name_en": "Cape Verde", "name_th": "เคปเวิร์ด"},
    "Central African Republic": {"iso2": "CF", "name_en": "Central African Republic", "name_th": "สาธารณรัฐแอฟริกากลาง"},
    "Chad": {"iso2": "TD", "name_en": "Chad", "name_th": "ชาด"},
    "Chile": {"iso2": "CL", "name_en": "Chile", "name_th": "ชิลี"},
    "China": {"iso2": "CN", "name_en": "China", "name_th": "จีน"},
    "Colombia": {"iso2": "CO", "name_en": "Colombia", "name_th": "โคลอมเบีย"},
    "Comoros": {"iso2": "KM", "name_en": "Comoros", "name_th": "คอโมโรส"},
    "Congo": {"iso2": "CG", "name_en": "Congo", "name_th": "คองโก"},
    "Congo (Dem. Rep.)": {"iso2": "CD", "name_en": "DR Congo", "name_th": "สาธารณรัฐประชาธิปไตยคองโก"},
    "DR Congo": {"iso2": "CD", "name_en": "DR Congo", "name_th": "สาธารณรัฐประชาธิปไตยคองโก"},
    "Costa Rica": {"iso2": "CR", "name_en": "Costa Rica", "name_th": "คอสตาริกา"},
    "Cote d'Ivoire (Ivory Coast)": {"iso2": "CI", "name_en": "Ivory Coast", "name_th": "โกตดิวัวร์"},
    "Ivory Coast": {"iso2": "CI", "name_en": "Ivory Coast", "name_th": "โกตดิวัวร์"},
    "Croatia": {"iso2": "HR", "name_en": "Croatia", "name_th": "โครเอเชีย"},
    "Cuba": {"iso2": "CU", "name_en": "Cuba", "name_th": "คิวบา"},
    "Cyprus": {"iso2": "CY", "name_en": "Cyprus", "name_th": "ไซปรัส"},
    "Czech Republic": {"iso2": "CZ", "name_en": "Czech Republic", "name_th": "เช็ก"},
    "Denmark": {"iso2": "DK", "name_en": "Denmark", "name_th": "เดนมาร์ก"},
    "Djibouti": {"iso2": "DJ", "name_en": "Djibouti", "name_th": "จิบูตี"},
    "Dominica": {"iso2": "DM", "name_en": "Dominica", "name_th": "ดอมินีกา"},
    "Dominican Republic": {"iso2": "DO", "name_en": "Dominican Republic", "name_th": "สาธารณรัฐโดมินิกัน"},
    "Ecuador": {"iso2": "EC", "name_en": "Ecuador", "name_th": "เอกวาดอร์"},
    "Egypt": {"iso2": "EG", "name_en": "Egypt", "name_th": "อียิปต์"},
    "El Salvador": {"iso2": "SV", "name_en": "El Salvador", "name_th": "เอลซัลวาดอร์"},
    "Equatorial Guinea": {"iso2": "GQ", "name_en": "Equatorial Guinea", "name_th": "อิเควทอเรียลกินี"},
    "Eritrea": {"iso2": "ER", "name_en": "Eritrea", "name_th": "เอริเทรีย"},
    "Estonia": {"iso2": "EE", "name_en": "Estonia", "name_th": "เอสโตเนีย"},
    "Eswatini": {"iso2": "SZ", "name_en": "Eswatini", "name_th": "เอสวาตินี"},
    "Swaziland": {"iso2": "SZ", "name_en": "Eswatini", "name_th": "เอสวาตินี"},
    "Ethiopia": {"iso2": "ET", "name_en": "Ethiopia", "name_th": "เอธิโอเปีย"},
    "Fiji": {"iso2": "FJ", "name_en": "Fiji", "name_th": "ฟิจิ"},
    "Finland": {"iso2": "FI", "name_en": "Finland", "name_th": "ฟินแลนด์"},
    "France": {"iso2": "FR", "name_en": "France", "name_th": "ฝรั่งเศส"},
    "Gabon": {"iso2": "GA", "name_en": "Gabon", "name_th": "กาบอง"},
    "Gambia": {"iso2": "GM", "name_en": "Gambia", "name_th": "แกมเบีย"},
    "Georgia": {"iso2": "GE", "name_en": "Georgia", "name_th": "จอร์เจีย"},
    "Germany": {"iso2": "DE", "name_en": "Germany", "name_th": "เยอรมนี"},
    "Ghana": {"iso2": "GH", "name_en": "Ghana", "name_th": "กานา"},
    "Greece": {"iso2": "GR", "name_en": "Greece", "name_th": "กรีซ"},
    "Grenada": {"iso2": "GD", "name_en": "Grenada", "name_th": "เกรเนดา"},
    "Guatemala": {"iso2": "GT", "name_en": "Guatemala", "name_th": "กัวเตมาลา"},
    "Guinea": {"iso2": "GN", "name_en": "Guinea", "name_th": "กินี"},
    "Guinea-Bissau": {"iso2": "GW", "name_en": "Guinea-Bissau", "name_th": "กินี-บิสเซา"},
    "Guyana": {"iso2": "GY", "name_en": "Guyana", "name_th": "กายอานา"},
    "Haiti": {"iso2": "HT", "name_en": "Haiti", "name_th": "เฮติ"},
    "Honduras": {"iso2": "HN", "name_en": "Honduras", "name_th": "ฮอนดูรัส"},
    "Hong Kong": {"iso2": "HK", "name_en": "Hong Kong", "name_th": "ฮ่องกง"},
    "Hungary": {"iso2": "HU", "name_en": "Hungary", "name_th": "ฮังการี"},
    "Iceland": {"iso2": "IS", "name_en": "Iceland", "name_th": "ไอซ์แลนด์"},
    "India": {"iso2": "IN", "name_en": "India", "name_th": "อินเดีย"},
    "Indonesia": {"iso2": "ID", "name_en": "Indonesia", "name_th": "อินโดนีเซีย"},
    "Iran": {"iso2": "IR", "name_en": "Iran", "name_th": "อิหร่าน"},
    "Iraq": {"iso2": "IQ", "name_en": "Iraq", "name_th": "อิรัก"},
    "Ireland": {"iso2": "IE", "name_en": "Ireland", "name_th": "ไอร์แลนด์"},
    "Israel": {"iso2": "IL", "name_en": "Israel", "name_th": "อิสราเอล"},
    "Italy": {"iso2": "IT", "name_en": "Italy", "name_th": "อิตาลี"},
    "Jamaica": {"iso2": "JM", "name_en": "Jamaica", "name_th": "จาเมกา"},
    "Japan": {"iso2": "JP", "name_en": "Japan", "name_th": "ญี่ปุ่น"},
    "Jordan": {"iso2": "JO", "name_en": "Jordan", "name_th": "จอร์แดน"},
    "Kazakhstan": {"iso2": "KZ", "name_en": "Kazakhstan", "name_th": "คาซัคสถาน"},
    "Kenya": {"iso2": "KE", "name_en": "Kenya", "name_th": "เคนยา"},
    "Kiribati": {"iso2": "KI", "name_en": "Kiribati", "name_th": "คิริบาส"},
    "Kosovo": {"iso2": "XK", "name_en": "Kosovo", "name_th": "คอซอวอ"},
    "Kuwait": {"iso2": "KW", "name_en": "Kuwait", "name_th": "คูเวต"},
    "Kyrgyzstan": {"iso2": "KG", "name_en": "Kyrgyzstan", "name_th": "คีร์กีซสถาน"},
    "Laos": {"iso2": "LA", "name_en": "Laos", "name_th": "ลาว"},
    "Latvia": {"iso2": "LV", "name_en": "Latvia", "name_th": "ลัตเวีย"},
    "Lebanon": {"iso2": "LB", "name_en": "Lebanon", "name_th": "เลบานอน"},
    "Lesotho": {"iso2": "LS", "name_en": "Lesotho", "name_th": "เลโซโท"},
    "Liberia": {"iso2": "LR", "name_en": "Liberia", "name_th": "ไลบีเรีย"},
    "Libya": {"iso2": "LY", "name_en": "Libya", "name_th": "ลิเบีย"},
    "Liechtenstein": {"iso2": "LI", "name_en": "Liechtenstein", "name_th": "ลิกเตนสไตน์"},
    "Lithuania": {"iso2": "LT", "name_en": "Lithuania", "name_th": "ลิทัวเนีย"},
    "Luxembourg": {"iso2": "LU", "name_en": "Luxembourg", "name_th": "ลักเซมเบิร์ก"},
    "Macao": {"iso2": "MO", "name_en": "Macao", "name_th": "มาเก๊า"},
    "Madagascar": {"iso2": "MG", "name_en": "Madagascar", "name_th": "มาดากัสการ์"},
    "Malawi": {"iso2": "MW", "name_en": "Malawi", "name_th": "มาลาวี"},
    "Malaysia": {"iso2": "MY", "name_en": "Malaysia", "name_th": "มาเลเซีย"},
    "Maldives": {"iso2": "MV", "name_en": "Maldives", "name_th": "มัลดีฟส์"},
    "Mali": {"iso2": "ML", "name_en": "Mali", "name_th": "มาลี"},
    "Malta": {"iso2": "MT", "name_en": "Malta", "name_th": "มอลตา"},
    "Marshall Islands": {"iso2": "MH", "name_en": "Marshall Islands", "name_th": "หมู่เกาะมาร์แชลล์"},
    "Mauritania": {"iso2": "MR", "name_en": "Mauritania", "name_th": "มอริเตเนีย"},
    "Mauritius": {"iso2": "MU", "name_en": "Mauritius", "name_th": "มอริเชียส"},
    "Mexico": {"iso2": "MX", "name_en": "Mexico", "name_th": "เม็กซิโก"},
    "Micronesia": {"iso2": "FM", "name_en": "Micronesia", "name_th": "ไมโครนีเซีย"},
    "Moldova": {"iso2": "MD", "name_en": "Moldova", "name_th": "มอลโดวา"},
    "Monaco": {"iso2": "MC", "name_en": "Monaco", "name_th": "โมนาโก"},
    "Mongolia": {"iso2": "MN", "name_en": "Mongolia", "name_th": "มองโกเลีย"},
    "Montenegro": {"iso2": "ME", "name_en": "Montenegro", "name_th": "มอนเตเนโกร"},
    "Morocco": {"iso2": "MA", "name_en": "Morocco", "name_th": "โมร็อกโก"},
    "Mozambique": {"iso2": "MZ", "name_en": "Mozambique", "name_th": "โมซัมบิก"},
    "Myanmar": {"iso2": "MM", "name_en": "Myanmar", "name_th": "เมียนมา"},
    "Namibia": {"iso2": "NA", "name_en": "Namibia", "name_th": "นามิเบีย"},
    "Nauru": {"iso2": "NR", "name_en": "Nauru", "name_th": "นาอูรู"},
    "Nepal": {"iso2": "NP", "name_en": "Nepal", "name_th": "เนปาล"},
    "Netherlands": {"iso2": "NL", "name_en": "Netherlands", "name_th": "เนเธอร์แลนด์"},
    "New Zealand": {"iso2": "NZ", "name_en": "New Zealand", "name_th": "นิวซีแลนด์"},
    "Nicaragua": {"iso2": "NI", "name_en": "Nicaragua", "name_th": "นิการากัว"},
    "Niger": {"iso2": "NE", "name_en": "Niger", "name_th": "ไนเจอร์"},
    "Nigeria": {"iso2": "NG", "name_en": "Nigeria", "name_th": "ไนจีเรีย"},
    "North Korea": {"iso2": "KP", "name_en": "North Korea", "name_th": "เกาหลีเหนือ"},
    "North Macedonia": {"iso2": "MK", "name_en": "North Macedonia", "name_th": "มาซิโดเนียเหนือ"},
    "Norway": {"iso2": "NO", "name_en": "Norway", "name_th": "นอร์เวย์"},
    "Oman": {"iso2": "OM", "name_en": "Oman", "name_th": "โอมาน"},
    "Pakistan": {"iso2": "PK", "name_en": "Pakistan", "name_th": "ปากีสถาน"},
    "Palau": {"iso2": "PW", "name_en": "Palau", "name_th": "ปาเลา"},
    "Palestine": {"iso2": "PS", "name_en": "Palestine", "name_th": "ปาเลสไตน์"},
    "Palestinian Territories": {"iso2": "PS", "name_en": "Palestine", "name_th": "ปาเลสไตน์"},
    "Panama": {"iso2": "PA", "name_en": "Panama", "name_th": "ปานามา"},
    "Papua New Guinea": {"iso2": "PG", "name_en": "Papua New Guinea", "name_th": "ปาปัวนิวกินี"},
    "Paraguay": {"iso2": "PY", "name_en": "Paraguay", "name_th": "ปารากวัย"},
    "Peru": {"iso2": "PE", "name_en": "Peru", "name_th": "เปรู"},
    "Philippines": {"iso2": "PH", "name_en": "Philippines", "name_th": "ฟิลิปปินส์"},
    "Poland": {"iso2": "PL", "name_en": "Poland", "name_th": "โปแลนด์"},
    "Portugal": {"iso2": "PT", "name_en": "Portugal", "name_th": "โปรตุเกส"},
    "Qatar": {"iso2": "QA", "name_en": "Qatar", "name_th": "กาตาร์"},
    "Romania": {"iso2": "RO", "name_en": "Romania", "name_th": "โรมาเนีย"},
    "Russia": {"iso2": "RU", "name_en": "Russia", "name_th": "รัสเซีย"},
    "Russian Federation": {"iso2": "RU", "name_en": "Russia", "name_th": "รัสเซีย"},
    "Rwanda": {"iso2": "RW", "name_en": "Rwanda", "name_th": "รวันดา"},
    "Saint Kitts and Nevis": {"iso2": "KN", "name_en": "Saint Kitts and Nevis", "name_th": "เซนต์คิตส์และเนวิส"},
    "Saint Lucia": {"iso2": "LC", "name_en": "Saint Lucia", "name_th": "เซนต์ลูเชีย"},
    "Saint Vincent and the Grenadines": {"iso2": "VC", "name_en": "Saint Vincent", "name_th": "เซนต์วินเซนต์และเกรนาดีนส์"},
    "St. Vincent and the Grenadines": {"iso2": "VC", "name_en": "Saint Vincent", "name_th": "เซนต์วินเซนต์และเกรนาดีนส์"},
    "Samoa": {"iso2": "WS", "name_en": "Samoa", "name_th": "ซามัว"},
    "San Marino": {"iso2": "SM", "name_en": "San Marino", "name_th": "ซานมารีโน"},
    "Sao Tome and Principe": {"iso2": "ST", "name_en": "Sao Tome and Principe", "name_th": "เซาตูเมและปรินซิปี"},
    "Saudi Arabia": {"iso2": "SA", "name_en": "Saudi Arabia", "name_th": "ซาอุดีอาระเบีย"},
    "Senegal": {"iso2": "SN", "name_en": "Senegal", "name_th": "เซเนกัล"},
    "Serbia": {"iso2": "RS", "name_en": "Serbia", "name_th": "เซอร์เบีย"},
    "Seychelles": {"iso2": "SC", "name_en": "Seychelles", "name_th": "เซเชลส์"},
    "Sierra Leone": {"iso2": "SL", "name_en": "Sierra Leone", "name_th": "เซียร์ราลีโอน"},
    "Singapore": {"iso2": "SG", "name_en": "Singapore", "name_th": "สิงคโปร์"},
    "Slovakia": {"iso2": "SK", "name_en": "Slovakia", "name_th": "สโลวาเกีย"},
    "Slovenia": {"iso2": "SI", "name_en": "Slovenia", "name_th": "สโลวีเนีย"},
    "Solomon Islands": {"iso2": "SB", "name_en": "Solomon Islands", "name_th": "หมู่เกาะโซโลมอน"},
    "Somalia": {"iso2": "SO", "name_en": "Somalia", "name_th": "โซมาเลีย"},
    "South Africa": {"iso2": "ZA", "name_en": "South Africa", "name_th": "แอฟริกาใต้"},
    "South Korea": {"iso2": "KR", "name_en": "South Korea", "name_th": "เกาหลีใต้"},
    "South Sudan": {"iso2": "SS", "name_en": "South Sudan", "name_th": "ซูดานใต้"},
    "Spain": {"iso2": "ES", "name_en": "Spain", "name_th": "สเปน"},
    "Sri Lanka": {"iso2": "LK", "name_en": "Sri Lanka", "name_th": "ศรีลังกา"},
    "Sudan": {"iso2": "SD", "name_en": "Sudan", "name_th": "ซูดาน"},
    "Suriname": {"iso2": "SR", "name_en": "Suriname", "name_th": "ซูรินาม"},
    "Sweden": {"iso2": "SE", "name_en": "Sweden", "name_th": "สวีเดน"},
    "Switzerland": {"iso2": "CH", "name_en": "Switzerland", "name_th": "สวิตเซอร์แลนด์"},
    "Syria": {"iso2": "SY", "name_en": "Syria", "name_th": "ซีเรีย"},
    "Taiwan": {"iso2": "TW", "name_en": "Taiwan", "name_th": "ไต้หวัน"},
    "Tajikistan": {"iso2": "TJ", "name_en": "Tajikistan", "name_th": "ทาจิกิสถาน"},
    "Tanzania": {"iso2": "TZ", "name_en": "Tanzania", "name_th": "แทนซาเนีย"},
    "Thailand": {"iso2": "TH", "name_en": "Thailand", "name_th": "ไทย"},
    "Timor-Leste": {"iso2": "TL", "name_en": "Timor-Leste", "name_th": "ติมอร์-เลสเต"},
    "Togo": {"iso2": "TG", "name_en": "Togo", "name_th": "โตโก"},
    "Tonga": {"iso2": "TO", "name_en": "Tonga", "name_th": "ตองกา"},
    "Trinidad and Tobago": {"iso2": "TT", "name_en": "Trinidad and Tobago", "name_th": "ตรินิแดดและโตเบโก"},
    "Tunisia": {"iso2": "TN", "name_en": "Tunisia", "name_th": "ตูนิเซีย"},
    "Turkey": {"iso2": "TR", "name_en": "Turkey", "name_th": "ตุรกี"},
    "Turkmenistan": {"iso2": "TM", "name_en": "Turkmenistan", "name_th": "เติร์กเมนิสถาน"},
    "Tuvalu": {"iso2": "TV", "name_en": "Tuvalu", "name_th": "ตูวาลู"},
    "Uganda": {"iso2": "UG", "name_en": "Uganda", "name_th": "ยูกันดา"},
    "Ukraine": {"iso2": "UA", "name_en": "Ukraine", "name_th": "ยูเครน"},
    "United Arab Emirates": {"iso2": "AE", "name_en": "United Arab Emirates", "name_th": "สหรัฐอาหรับเอมิเรตส์"},
    "United Kingdom": {"iso2": "GB", "name_en": "United Kingdom", "name_th": "สหราชอาณาจักร"},
    "United States": {"iso2": "US", "name_en": "United States", "name_th": "สหรัฐอเมริกา"},
    "United States of America": {"iso2": "US", "name_en": "United States", "name_th": "สหรัฐอเมริกา"},
    "Uruguay": {"iso2": "UY", "name_en": "Uruguay", "name_th": "อุรุกวัย"},
    "Uzbekistan": {"iso2": "UZ", "name_en": "Uzbekistan", "name_th": "อุซเบกิสถาน"},
    "Vanuatu": {"iso2": "VU", "name_en": "Vanuatu", "name_th": "วานูอาตู"},
    "Vatican": {"iso2": "VA", "name_en": "Vatican City", "name_th": "นครรัฐวาติกัน"},
    "Vatican City": {"iso2": "VA", "name_en": "Vatican City", "name_th": "นครรัฐวาติกัน"},
    "Venezuela": {"iso2": "VE", "name_en": "Venezuela", "name_th": "เวเนซุเอลา"},
    "Vietnam": {"iso2": "VN", "name_en": "Vietnam", "name_th": "เวียดนาม"},
    "Viet Nam": {"iso2": "VN", "name_en": "Vietnam", "name_th": "เวียดนาม"},
    "Yemen": {"iso2": "YE", "name_en": "Yemen", "name_th": "เยเมน"},
    "Zambia": {"iso2": "ZM", "name_en": "Zambia", "name_th": "แซมเบีย"},
    "Zimbabwe": {"iso2": "ZW", "name_en": "Zimbabwe", "name_th": "ซิมบับเว"}
}
